server:
  port: 9090

spring:
  datasource:
       url: jdbc:mysql://localhost:3306/ts?serverTimezone=GMT%2b8
       driver-class-name: com.mysql.cj.jdbc.Driver
       username: root
       password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true # 开取数据库字段下划线转驼峰

